name: build and deploy website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /lies-of-p-checklist

      - name: Export
        run: npm run export
        env:
          NEXT_PUBLIC_BASE_PATH: /lies-of-p-checklist

      - run: touch ./out/.nojekyll

      - name: Deploy
        uses: ishan0445/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
